# Generated by Django 4.0.3 on 2022-03-06 02:27

import api_server.lib.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=api_server.lib.models.base.ulid_new_proxy, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(default='')),
                ('is_public', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=api_server.lib.models.base.ulid_new_proxy, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('message', models.CharField(default='', max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
