# Generated by Django 4.0.3 on 2022-05-08 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_active_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
