# Generated by Django 4.0.3 on 2022-05-14 04:29

import api_server.lib.models.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_room_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='score',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(default=api_server.lib.models.base.ulid_new_proxy, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('count', models.PositiveIntegerField(blank=True, default=0)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='chat.tweet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
